apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: angular-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: 18.211.214.106
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: angular-demo-service
              port:
                number: 80
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: spring-service
              port:
                number: 8080
