name: Build and Deploy to Docker Hub & Kubernetes

on:
  push:
    branches: [ master ]

env:
  IMAGE_NAME: angular-demo-app
  DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/angular-demo-app

jobs:
  build-deploy:
    runs-on: self-hosted
    env:
      KUBECONFIG: /home/ubuntu/.kube/config

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t $DOCKER_REPO:latest .
          docker push $DOCKER_REPO:latest

      - name: Set up kubectl (self-managed cluster)
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Wait for Kubernetes to be ready
        run: |
          echo "Waiting for Kubernetes API..."
          for i in {1..30}; do
            if kubectl get nodes > /dev/null 2>&1; then
              echo "Kubernetes is ready."
              break
            fi
            echo "Waiting ($i)..."
            sleep 5
          done

      - name: Ensure Ingress-NGINX is installed
        run: |
          if helm list -q | grep -w ingress-nginx; then
            echo "Uninstalling existing ingress-nginx Helm release..."
            helm uninstall ingress-nginx
          fi
          echo "Installing ingress-nginx via Helm..."
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm install ingress-nginx ingress-nginx/ingress-nginx --set controller.admissionWebhooks.enabled=false

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

          kubectl delete ingress angular-ingress --ignore-not-found=true
          kubectl apply -f k8s/ingress.yaml --validate=false

      - name: Clean up unused Docker images
        run: docker image prune -f
