name: Build and Deploy to Docker Hub & Kubernetes

on:
  push:
    branches: [ master ]

env:
  IMAGE_NAME: angular-demo-app
  DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/angular-demo-app

jobs:
  build-deploy:
    runs-on: self-hosted
    env:
      KUBECONFIG: /home/ubuntu/.kube/config

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t $DOCKER_REPO:latest .
          docker push $DOCKER_REPO:latest

      - name: Set up kubectl (self-managed cluster)
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Wait for Kubernetes to be ready
        run: |
          echo "Waiting for Kubernetes API..."
          for i in {1..30}; do
            if kubectl get nodes > /dev/null 2>&1; then
              echo "Kubernetes is ready."
              break
            fi
            echo "Waiting ($i)..."
            sleep 5
          done
        env:
          KUBECONFIG: /home/ubuntu/.kube/config

      - name: Ensure Ingress-NGINX is installed
        run: |
          if ! kubectl get ns ingress-nginx > /dev/null 2>&1; then
            echo "Ingress NGINX not found. Installing..."
            kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.0/deploy/static/provider/cloud/deploy.yaml
            echo "Waiting for ingress-nginx controller to be ready..."
            kubectl wait --namespace ingress-nginx \
              --for=condition=Ready pod \
              --selector=app.kubernetes.io/component=controller \
              --timeout=120s
          else
            echo "Ingress NGINX already installed."
          fi

          echo "Waiting for ingress-nginx controller to be ready..."
          kubectl rollout status deployment ingress-nginx-controller -n ingress-nginx

          echo "Waiting for admission jobs to complete..."
          kubectl wait --namespace ingress-nginx --for=condition=complete job/ingress-nginx-admission-create --timeout=60s
          kubectl wait --namespace ingress-nginx --for=condition=complete job/ingress-nginx-admission-patch --timeout=60s
          
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

          kubectl delete ingress angular-ingress --ignore-not-found=true
          kubectl apply -f k8s/ingress.yaml

      - name: Clean up unused Docker images
        run: docker image prune -f
